matrix:
  include:
  -
    language: python
    python:
    - '2.7'
    - '3.3'
    - '3.4'
    cache: pip
    install:
      - pip install pytest-cov
    script:
      - py.test --cov-report=xml term --cov=a2
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - 
    language: generic
    before_install:
    - openssl aes-256-cbc -K $encrypted_41a7558dcc5f_key -iv $encrypted_41a7558dcc5f_iv -in deploy_rsa.enc -out deploy_rsa -d
    addons:
      ssh_known_hosts: moon.scs.ryerson.ca
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_41a7558dcc5f_key -iv $encrypted_41a7558dcc5f_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    deploy:
      provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet ${TRAVIS_BUILD_DIR}/index.html ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/avm/courses/cps847/sdeljooy
      on:
        branch: master